set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=$TS_ENV_GIT/vim/bundle/Vundle.vim
call vundle#begin("$TS_ENV_HOME/vim/bundle")
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
"Plugin 'gmarik/Vundle.vim'

source $TS_ENV_HOME/vim/vimrcs/nerdtree.vimrc
source $TS_ENV_HOME/vim/vimrcs/airline.vimrc
source $TS_ENV_HOME/vim/vimrcs/taglist.vimrc
source $TS_ENV_HOME/vim/vimrcs/cscope.vimrc
source $TS_ENV_HOME/vim/vimrcs/youcompleteme.vimrc
source $TS_ENV_HOME/vim/vimrcs/easymotion.vimrc
source $TS_ENV_HOME/vim/vimrcs/ctrlp.vimrc
source $TS_ENV_HOME/vim/vimrcs/clang_format.vimrc
source $TS_ENV_HOME/vim/vimrcs/listtoggle.vimrc
source $TS_ENV_HOME/vim/vimrcs/indentLine.vimrc
source $TS_ENV_HOME/vim/vimrcs/syntastic.vimrc
source $TS_ENV_HOME/vim/vimrcs/molokai.vimrc


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
source $TS_ENV_HOME/vim/vimrcs/generic.vimrc
